apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
spec:
  data:
    POSTGRES_DB: "linkdb_staging"
    KAFKA_HOST: "staging-kafka.linkshortener-staging.svc.cluster.local"
    APP_BASE_URL: "https://staging-api.com/"
