apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkshortener-staging

namePrefix: staging-

resources:
  - ../../base
  - namespace.yaml

commonLabels:
  environment: staging

replicas:
  - name: postgres
    count: 1
  - name: kafka
    count: 1
  - name: zookeeper
    count: 1
  - name: linkshortener
    count: 2
  - name: linkshortener-analytics
    count: 1

patchesStrategicMerge:
  - postgres-config.yaml
  - kafka-config.yaml
  - configmap-patch.yaml
  - secrets-patch.yaml
