apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: linkshortener
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: client
  selector:
    app: kafka
  type: ClusterIP
