apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: linkshortener
data:
  POSTGRES_HOST: "postgres-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "linkdb"
  KAFKA_HOST: "kafka.linkshortener.svc.cluster.local"
  KAFKA_PORT: "9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  APP_PORT: "8080"
  APP_BASE_URL: "http://linkshortener.local/"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
