apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgresql/deployment.yaml
  - postgresql/service.yaml
  - kafka/deployment.yaml
  - kafka/service.yaml
  - linkshortener/deployment.yaml
  - linkshortener/service.yaml
  - linkshortener-analytics/deployment.yaml
  - linkshortener-analytics/service.yaml
  - ingress.yaml

commonLabels:
  project: linkshortener
