apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: linkshortener
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
  type: ClusterIP
